import {useState,useEffect} from 'react';
import MovieDB from '../api/MovieDB';
import { MovieFull } from '../interfaces/MovieInterfaces';
import { Cast, MovieCredits } from '../interfaces/CreditsInterface';

interface MovieDetails {
    isLoading: boolean;
    movieFull?: MovieFull;
    cast: Cast[];
}

export const UseMovieDetails = (movieId:number) => {
    const [state, setState] = useState<MovieDetails>({
        isLoading: true,
        movieFull: undefined,
        cast: []
    });

  const getMoviesDetails= async()=>{

    const movieDetailsPromise = MovieDB.get<MovieFull>(`/${ movieId }`);
     const castPromise = MovieDB.get<MovieCredits>(`/${ movieId }/credits`);
    
    const [ movieDetailsResp, castPromiseResp ] = await Promise.all([ movieDetailsPromise, castPromise ]);

    setState({
        isLoading: false,
        movieFull: movieDetailsResp.data,
        cast: castPromiseResp.data.cast
    })
  }

  useEffect(() => {
    getMoviesDetails();
  }, [])// Generated by https://quicktype.io



  
  return{
    ...state
  }
};


